apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: spring-petclinic-build
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "cicd-demo"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
      - name: basic-auth
    results:
      - name: APP_IMAGE_DIGETST
        description: The image digest built in the pipeline
        value: $(tasks.build-image.results.IMAGE_DIGEST)
    tasks:
      - name: source-clone
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: URL
            value: $(params.repo_url)
          - name: REVISION
            value: $(params.revision)
          - name: DEPTH
            value: "0"
          - name: SUBDIRECTORY
            value: spring-petclinic
      - name: mvn-config
        taskRef: 
          name: mvn-config
        runAfter:
          - source-clone
        workspaces:
        - name: workspace
          workspace: source
      - name: unit-tests
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        runAfter:
          - mvn-config
        workspaces:
        - name: source
          workspace: source
        - name: maven_settings
          workspace: source
        params:
        - name: GOALS
          value: ["package", "-f", "spring-petclinic"]
      - name: code-analysis
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        runAfter:
          - unit-tests
        workspaces:
        - name: source
          workspace: source
        - name: maven_settings
          workspace: source
        params:
        - name: GOALS
          value:
          - install
          - org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar
          - -f
          - spring-petclinic
          - -Dsonar.host.url=http://sonarqube:9000
          - -Dsonar.userHome=/tmp/sonar
          - -DskipTests=true
          - -Dsonar.qualitygate.wait=true
          - -Dsonar.login=admin
          - -Dsonar.password=sonarqube
      - name: security-scan
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        runAfter:
          - unit-tests
        workspaces:
        - name: source
          workspace: source
        - name: maven_settings
          workspace: source
        params:
        - name: GOALS
          value: ["--version", "-f", "spring-petclinic"]
      - name: release-app
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        runAfter:
          - code-analysis
          - security-scan
        workspaces:
        - name: source
          workspace: source
        - name: maven_settings
          workspace: source
        params:
        - name: GOALS
          value:
          - deploy
          - -f 
          - spring-petclinic
          - -DskipTests=true
          - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
          - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
          - -Durl=http://nexus:8081/repository/maven-releases/
          - -DrepositoryId=nexus
      - name: build-image
        taskRef:
          resolver: cluster
          params:
          - name: name
            value: s2i-java
          - name: namespace
            value: openshift-pipelines
          - name: kind
            value: task
        runAfter:
        - release-app
        params:
          - name: TLS_VERIFY
            value: "false"
          # - name: MAVEN_MIRROR_URL
            # value: http://nexus:8081/repository/maven-public/
          - name: CONTEXT
            value: spring-petclinic/target
          - name: IMAGE
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic:latest
          - name: IMAGE_SCRIPTS_URL
            value: "image:///usr/local/s2i"
        workspaces:
        - name: source
          workspace: source
      - name: update-manifests
        runAfter:
        - build-image
        taskRef:
          name: git-update-deployment
        params:
          - name: GIT_REPOSITORY
            value: https://github.com/rrahhal1/spring-petclinic-config
          - name: GIT_USERNAME
            value: gitea
          - name: GIT_PASSWORD
            value: openshift
          - name: CURRENT_IMAGE
            value: quay.io/siamaksade/spring-petclinic:latest
          - name: NEW_IMAGE
            value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spring-petclinic
          - name: NEW_DIGEST
            value: "$(tasks.build-image.results.IMAGE_DIGEST)"
          - name: KUSTOMIZATION_PATH
            value: environments/dev
        workspaces:
        - name: workspace
          workspace: source
      - name: pr-promote
        runAfter:
        - update-manifests
        taskRef:
          name: create-promote-pull-request
        params:
          - name: GIT_REPOSITORY
            value: https://github.com/rrahhal1/spring-petclinic-config
          - name: GIT_USERNAME
            value: gitea
          - name: GIT_PASSWORD
            value: openshift
          - name: COPY_FROM_PATH
            value: environments/dev
          - name: COPY_TO_PATH
            value: environments/stage
        workspaces:
        - name: workspace
          workspace: source
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
